-- DDL Script was generated by Orange for ORACLE

CREATE TABLE DAUSER.DA_OGG_PRM_FILE
(
    FILE_NM VARCHAR2(2000)
)
ORGANIZATION EXTERNAL 
(TYPE ORACLE_LOADER
DEFAULT DIRECTORY OGG_PREPROCESSOR_DIR
ACCESS PARAMETERS
(records delimited by newline
       preprocessor OGG_PREPROCESSOR_DIR:'oggFileListUnix.sh'
       FIELDS terminated BY ","
      )
LOCATION ( 'oggFileListUnix.sh' )
);
